name: ZombiesPlugin
version: ${project.version}
main: io.github.zap.zombiesplugin.ZombiesPlugin
api-version: 1.13
authors: [LimeSlayer420, thamid, TachibanaYui]
description: An improved version of the Hypixel minigame Zombies.
depend:
  - MythicMobs
commands:
  gunDebug:
    description: Test command related to guns
  gamemanager:
    description: Create game managers on demand, for testing purposes.
    usage: /manager add <id> or /manager list
  spawnmanager:
    description: Adds or removes a spawnpoint from the specified manager.
    usage: /spawnpoint add
  testentity:
    description: Spawns a testing zombie.
    usage: /testentity