name: ZombiesPlugin
version: ${project.version}
main: io.github.zap.zombiesplugin.ZombiesPlugin
api-version: "1.13"
authors: [LimeSlayer420, thamid, TachibanaYui]
description: An improved version of the Hypixel minigame Zombies.
depend:
  - MythicMobs
  - ProtocolLib
commands:
  equipmentDebug:
    description: Test command related to equipments
  invDebug:
    description: test mostly team machine
  setGold:
    description: Set player gold
  scoreBoardDebug:
    description: testScoreboard thingy
  newspawnpoint:
    description: Adds or removes a spawnpoint to the testing spawnpoint.
    usage: /newspawnpoint
  testentity:
    description: Spawns a testing zombie.
    usage: /testentity
  mapeditor:
    description: Command used to edit and create map configuration files.
  room:
    description: Creates a room.
  roomspawn:
    description: Creates room spawnpoints.
  windowspawn:
    description: Creates window spawnpoints.
  windowblocks:
    description: Creates window blocks.
  windowinterior:
    description: Creates window interior.
