name: ZombiesPlugin
version: ${project.version}
main: io.github.zap.zombiesplugin.ZombiesPlugin
api-version: 1.13
authors: [LimeSlayer420, thamid, TachibanaYui]
description: An improved version of the Hypixel minigame Zombies.
depend:
  - MythicMobs
commands:
  gunDebug:
    description: Test command related to guns
  newspawnpoint:
    description: Adds or removes a spawnpoint to the testing spawnpoint.
    usage: /newspawnpoint
  testentity:
    description: Spawns a testing zombie.
    usage: /testentity
