name: ZombiesPlugin
version: ${project.version}
main: io.github.zap.zombiesplugin.ZombiesPlugin
api-version: "1.13"
authors: [LimeSlayer420, thamid, TachibanaYui]
description: An improved version of the Hypixel minigame Zombies.
depend:
  - MythicMobs
  - ProtocolLib
commands:
  gunDebug:
    description: Test command related to guns
  testspawnpoint:
    description: For testing.
    usage: /testspawnpoint
  testentity:
    description: Spawns a testing zombie.
    usage: /testentity
